### ISSUE TITLE
Implement quiz functionality

### ISSUE THREAD

**Issue by taylalex** [taylalex/AWSQuiz#17]
Children: #22 #23 

We need to implement the quiz functionality so that the user can play the game.  There are a few questions to consider when tackling this ticket:
- Is the quiz functionality going to be ran on the front-end or back-end? 
  - If back-end: the client will GET the service image with four options and will POST/PUT its choice to the server that will decide whether the chosen answer is correct. Score keeping among other stuff would happen server-side
  - If front-end: the client will GET the service image with four options (one defined as the correctAnswer) and client will decide whether the chosen answer is correct.. Score keeping among other stuff would happen client-side
  - The reason I have brought this up is if the game is executed client-side, whenever the options are sent to the user after triggering a GET, they will be able to see the correctAnswer in the server's response. This is something which may be too OTT to consider for just a small project. Thought it was an interesting restraint nonetheless.
- How do we load in the image and options of the current question into the React components?
  - The SVG images are currently stored so that it can easily be referenced as a background-image of a `<div>` component
- How is it determined which question the user is currently on?
- Are the questions loaded in all at once using one request to the API, or sequentially as they go through the quiz.

**Comment by RachelSwift** [comment]
1. Im happy for it to be either, i feel like doing the first option of it being back-end shows more consideration for security though, and ultimately if we have to talk about this on Friday we can maybe talk about that? This may mean we have to rethink the structure of the data being sent back to the user though on the question request.
2. Lets just set is as the background of a div component then, If the background URL is set in the page state that should allow it to be dynamic just fine. 
3. Perhaps in line with point 1 we will need some sort of UUID, therefore on the get answer request we can send the uuid?
4. I don't really know with this one. Are there any advantages of choosing one over the other?

**Comment by RachelSwift** [comment]
Notes from Huddle:

1. Provisional decision to move Quiz functionality to the backend
2. Images are in Divs
3. Questions are given a UUID (mongo may provide this), when a user clicks their answer it can send this ID with the answer they chose {uuid:<string>, answer:<string>}. Server can then filter the db by the ID to check the answer.
4. We can count the score progressively server side and send the whole score back at the end of the quiz
