### ISSUE TITLE
Add session(Id) functionality

### ISSUE THREAD

**Issue by taylalex** [taylalex/AWSQuiz#43]
We need a way to access a user's quiz score after they have completed the quiz. The original approach was going to be as so:
- The ScoreScreen is rendered post quiz completion
- The user's answers would be passed in as a prop
-  the POST /getScore API endpoint would be triggered that sends the answers and receives a score

I am proposing a different approach, where each quiz is associated with a sessionId (a UUID):
- Quiz start button is pressed, a UUID is generated and added as a query parameter -> DOMAIN_NAME/quiz/:sessionId
- Once the page has rendered, we will utilise useEffect() to create a session in a new table (sessions) within the AWSQuiz db that contains:
  - sessionId : string
  - completed : bool (set to false)
  - score : int
- Once the quiz has been completed, the answers are sent to the server using a POST ~~/getScore~~ /postAnswers with the sessionID
- The attached function will update the session object in the sessions db:
    - Calculate the score and update the score field.
    - Change completed to be true.
- When the score wants to be viewed, the user can access DOMAIN_NAME/score/:sessionId which will call the GET /getScore API endpoint and retrieve the associated score from the db.
- The score page will automatically be visited after the quiz has been completed.

**Comment by RachelSwift** [comment]
This sounds good as a first implementation of session ID, happy to press on with this. 
As we improve the quiz it might also be useful to look at session cookies although this will need greater thought as to how we implement it.
